### ISSUE TITLE
"Versions" section should be more clear

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-reference-manual#30]
"Portable Serialization - Versions" section should be improved since it is not clear how to use it. Is portable version configured globally and not per factory? what will happen if two clients use different versions? Perhaps a use-case would help.

**Comment by Serdaro** [comment]
@jerrinot , Will it be too much if I ask more topics that you want the related section would cover? I feel that there are more than 2 questions you ask in the Slack (included in the above issue description) and I need more specificity. Or, you can direct me by suggesting a use case which will tell everything while it is explained (e.g. 2 members with different versions and a whole another 2 clients with different versions).

**Comment by sancar** [comment]
-- Is portable version configured globally and not per factory?
It is global. All portable classes that are serialized via current node will get the global configured portable version. That has been said, we added VersionedPortable along the way. 
https://github.com/hazelcast/hazelcast/pull/2543
It looks like it appears only one javadocs for now. We may add detailed description for this too.  VersionedPortable enables to upgrade version per class rather then global version. If you need to update only one class you can use this interface. Basically its portable class will implement VersionedPortable rather than Portable, and user will give desired version via VersionedPortable.getClassVersion  

-- what will happen if two clients use different versions?
There are  couple of scenarios to explain. A new node joined the cluster with class modified and version is upgraded because of this modification.
1)  If a new field added,  objects put from new node will contain the new field. If new one, tries to get an object that is put from older nodes, it will get null for new added field. 

2) If a field is removed. In this case, old one should get null from the objects put from new node. 

3) A field type has changed. This will lead to IncompatibleClassChangeError unless modification is on builtin types and byte size of new field is less than or equal to the old one. Example allowed conversions
long => int , byte , char , short 
int => byte , char, short

Other classes that does not have any change on them will work same as before as if nothing changed.

**Comment by Serdaro** [comment]
Thanks a lot Sancar. I will add the compiled information into the related section.
