### ISSUE TITLE
Supported JVMs section needs to be clarified

### ISSUE THREAD

**Issue by zdehz** [hazelcast/hazelcast-reference-manual#797]
The `Supported JVMs` section in the Reference Manual is a bit confusing for supported OpenJDK.

https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#supported-jvms

I see that in 4.0 BETA-2 Reference Manual has been updated with the `OpenJDK` column but it may also include a piece of information for JDK version `12` and `13` if they are supported or not.

Also, there is a note (like `JDK not available yet`) under the `Oracle JDK` column for version `11`. Same in the new Reference Manual as well: https://docs.hazelcast.org/docs/4.0-BETA-2/manual/html-single/index.html#supported-jvms

**Comment by Serdaro** [comment]
@Holmistr , I think I will need a helping hand on this one.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/2f87c26760170e22ed5f880fafe900485c0505a0

**Comment by JakeSCahill** [comment]
@zdehz @Serdaro, an open question before I get going:

I notice that we list support for other versions of Hazelcast IMDG. As a new user, it makes the table look confusing since the manuals are already versioned. I expect to just see JVM support for a specific version (in this case the latest 4.1). Is this something that users have requested or found useful?

**Comment by Serdaro** [comment]
Agreed up to some extent @JakeSCahill , I'd say let's rewrite the related section/rearrange the table so that it talks about only 4.1. However, some of our users use the older versions but want to look at the latest manual. We can rewrite the section for 4.1 and add a note something like "If you are using a previous Hazelcast version, check the related version's manual for the supported JVMs". Or, we can keep it as it is for now (adding the JDK 12 & 13 information), and enhance the concept during the revamp project. I'd go with the former option.

**Comment by JakeSCahill** [comment]
Sounds good. I'll go ahead. Thanks @Serdaro !
